user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

commande:
    resource: "@CommandeBundle/Resources/config/routing.yml"
    prefix:   /commande

produit:
    resource: "@ProduitBundle/Resources/config/routing.yml"
    prefix:   /produit

livraison:
    resource: "@LivraisonBundle/Resources/config/routing.yml"
    prefix:   /livraison

qr:
    resource: "@QRBundle/Resources/config/routing.yml"
    prefix:   /qr

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /blog

global:
    resource: "@GlobalBundle/Resources/config/routing.yml"
    prefix:   /global

event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /event

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"